Add support for LDAP authentication
stackabletech/superset-operator pull request #180
Opened 2022-04-21 12:40 UTC by sbernauer

## Description

Superseding https://github.com/stackabletech/superset-operator/pull/145, completely reworked to use new configuration mechanism introduced in https://github.com/stackabletech/superset-operator/pull/173
For https://github.com/stackabletech/superset-operator/issues/5
Integration-Tests: https://github.com/stackabletech/integration-tests/pull/175
Use `./create_test_cluster.py --kind --operator superset=0.4.0-prXXX` before running the tests

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-04-21 13:44 UTC, sbernauer commented
Integration tests are green => ready for review :)

2022-04-22 07:20 UTC, sbernauer commented on rust/operator-binary/src/config.rs
> +    );
Smoke tests do all pass not it seems to work fine. Solution is far from ideal anyway.

2022-04-25 15:26 UTC, maltesander reviewed
Just a small thing. Ran the tests and works. Maybe @siegfriedweber can have another look? Im not that into ldap and superset ;)

@sbernauer i cannot judge how good i is, but since we will required ldap etc in other operators to i think its fine to merge in a working approach and refine / improve that later as well.

2022-04-26 06:41 UTC, sbernauer commented on rust/operator-binary/src/superset_controller.rs
> +                cb.add_volume_mount(&volume_name, format!("/stackable/secrets/{volume_name}"));
Good point, thx

2022-05-03 13:09 UTC, siegfriedweber requested changes

2022-05-03 13:19 UTC, sbernauer commented on rust/operator-binary/src/config.rs
> +    );
Good hint, thanks!

2022-05-03 14:06 UTC, sbernauer commented on examples/superset-with-ldap.yaml
> +              value: user01,user02
Authorization was intentionally not included in this PR. I know that having all user assigned the Public role is not really usable but it's a secure default at the moment. The role can be set by the user to e.g. make all users Gamma.
I would expect Authorization (e.g. via LDAP group memberships) in a follow-up PR.
The line you commented here is btw from the bitnami opernldap container and is just to create 2 testusers in the LDAP instance.

2022-05-04 08:48 UTC, sbernauer commented on examples/superset-with-ldap.yaml
> +# Until commons-operator is available officially: helm install --version 0.1.0-pr11 --repo https://repo.stackable.tech/repository/helm-test/ commons-operator commons-operator
ack

2022-05-04 12:30 UTC, sbernauer commented on rust/crd/src/lib.rs
> +    /// Gets mapped to `AUTH_USER_REGISTRATION`
Test comment

2022-05-04 12:39 UTC, sbernauer commented on rust/crd/src/lib.rs
> +    pub methods: Vec<SupersetClusterAuthenticationConfigMethod>,
As other operators also don't have an simple list (e.g. current Zookeeper discussion) we will make this an `authenticationConfig: Option<SupersetClusterAuthenticationConfigMethod>`

2022-05-04 13:00 UTC, sbernauer commented on rust/crd/src/lib.rs
> +    pub methods: Vec<SupersetClusterAuthenticationConfigMethod>,
We agreeed on 
```
    authenticationConfig: # optional
      authenticationClass: superset-with-ldap-server-veri-tls-ldap # optional. If not set, AUTH_DB is used
      userRegistration: true # default true
      userRegistrationRole: Public # default Public

2022-05-04 13:11 UTC, sbernauer commented on examples/superset-with-ldap.yaml
> +              value: user01,user02
We add the Admin role in the example

2022-05-05 08:18 UTC, sbernauer commented on examples/superset-with-ldap.yaml
> +# Until commons-operator is available officially: helm install --version 0.1.0-pr11 --repo https://repo.stackable.tech/repository/helm-test/ commons-operator commons-operator
commons-operator 0.1.0 released :)

2022-05-05 10:32 UTC, sbernauer commented on examples/superset-with-ldap.yaml
> +        # autoGenerate: true # Needed in a future secret-operator version
secret-operator 0.3.0 released, example adopted

2022-05-05 13:11 UTC, sbernauer commented on rust/crd/src/lib.rs
> +    pub sync_roles_at: LdapRolesSyncMoment,
With the default value they are effective optional with the benefit of having well-documented defaults in the CRD.

2022-05-05 13:12 UTC, sbernauer commented
@siegfriedweber could you please take another look?

2022-05-09 13:07 UTC, siegfriedweber requested changes
There are some minor and one major issue left.

The major issue is that some views are not accessible by the administrator, e.g. the user list. The reason is that the `Admin` role does not have the `UserLDAPModelView` permission. The command `superset init` which is called in the job created by the `superset_db_controller` initializes the roles according to the configured authentication type. If the authentication type is `AUTH_LDAP` then the permission `UserLDAPModelView` is added to the `Admin` role. Unfortunately the authentication type is not set in the configuration created by the `superset_db_controller` and it is not trivial to add it.

2022-05-11 08:23 UTC, sbernauer commented
> The major issue is that some views are not accessible by the administrator, e.g. the user list. 

The problem should now be sorted out via https://github.com/stackabletech/superset-operator/pull/180/commits/458b7f2e0f4520ea98b37c3849769ad6cb138ed1

The problem with the first login failing is purely a bug in flask-appbuilder and should be fixed by https://github.com/dpgaspar/Flask-AppBuilder/pull/1846 which is entirely a docker image thing and not part of this PR.

Could you please take another look - would be great before your holiday to get this in :innocent:

2022-05-11 08:36 UTC, sbernauer commented on rust/operator-binary/src/main.rs
> +    false
Thanks for the tip!

2022-05-12 15:35 UTC, adwk67 approved these changes
lgtm. Opened a separate issue #195 to avoid db-clashes in the tests

2022-05-13 07:58 UTC, sbernauer commented
Thanks all for your feedback!
Everything should work to the best of my knowledge. Together with https://github.com/stackabletech/docker-images/pull/116 this seems to be a nice solution :)
The Authorization part is outstanding and will be handled via a separate PR.

2022-05-13 07:58 UTC, sbernauer commented
bors r+

2022-05-13 08:05 UTC, sbernauer commented
bors r+

2022-05-13 08:09 UTC, closed without merging