[Merged by Bors] - OpenShift compatibility
stackabletech/superset-operator pull request #352
Opened 2023-04-12 15:40 UTC by razvan

2023-04-13 11:02 UTC, maltesander requested changes
Minor things. LGTM otherwise!

2023-04-13 11:02 UTC, maltesander commented on rust/operator-binary/src/superset_controller.rs
> +    #[snafu(display("failed to patch role binding: {source}"))]
```suggestion
    #[snafu(display("failed to patch role binding"))]
```

2023-04-13 14:50 UTC, maltesander approved these changes
LGTM!

2023-04-14 08:01 UTC, maltesander commented on rust/operator-binary/src/druid_connection_controller.rs
> +    #[snafu(display("failed to patch role binding: {source}"))]
```suggestion
    #[snafu(display("failed to patch role binding"))]
```

2023-04-14 08:01 UTC, maltesander commented on rust/operator-binary/src/druid_connection_controller.rs
> +        .with_context(|_| ApplyRoleBindingSnafu)?;
```suggestion
    let (rbac_sa, rbac_rolebinding) =
        rbac::build_rbac_resources(druid_connection.as_ref(), APP_NAME);
    client
        .apply_patch(DRUID_CONNECTION_CONTROLLER_NAME, &rbac_sa, &rbac_sa)
        .await
        .context(ApplyServiceAccountSnafu)?;
    client
        .apply_patch(
            DRUID_CONNECTION_CONTROLLER_NAME,
            &rbac_rolebinding,
            &rbac_rolebinding,
        )
        .await
        .context(ApplyRoleBindingSnafu)?;
```

2023-04-14 08:35 UTC, razvan commented
CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/superset-operator-it-custom/34/

2023-04-14 13:39 UTC, razvan commented
bors merge

2023-04-14 13:46 UTC, closed without merging