Error if cerdentials Secret not found
stackabletech/superset-operator pull request #375
Opened 2023-06-27 12:46 UTC by Maleware

# Description

Fixing operator errors out if cerdentials Secret not found

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2023-06-27 14:25 UTC, sbernauer approved these changes
LGTM

2023-06-27 14:50 UTC, maltesander requested changes

2023-06-27 14:50 UTC, maltesander commented on rust/operator-binary/src/superset_db_controller.rs
> +                    .get_opt::<Secret>(&superset_db.spec.credentials_secret, &namespace)
```suggestion
                    .get::<Secret>(&superset_db.spec.credentials_secret, &namespace)
```

2023-06-27 16:34 UTC, sbernauer approved these changes

2023-06-28 07:29 UTC, maltesander approved these changes
Thanks! LGTM!

2023-06-28 07:31 UTC, Maleware commented
bors r+

2023-06-28 07:38 UTC, closed without merging