document pod overrides
stackabletech/superset-operator pull request #545
Opened 2024-09-19 14:04 UTC by fhennig

2024-09-19 14:48 UTC, adwk67 requested changes
Just minor things.

2024-09-19 14:48 UTC, adwk67 commented on docs/modules/superset/pages/getting_started/first_steps.adoc
> +WARNING: This setup is not suitable for production use.
```suggestion
WARNING: This setup is not suitable for use in production.
```

2024-09-19 14:48 UTC, adwk67 commented on docs/modules/superset/pages/getting_started/first_steps.adoc
> +The `connections.secretKey` will be used for securely signing the session cookies and can be used for any other security-related needs by extensions.
```suggestion
The `connections.secretKey` will be used for securely signing the session cookies and can be used by the extensions for any other security-related needs.
```

2024-09-19 14:48 UTC, adwk67 commented on docs/modules/superset/pages/getting_started/first_steps.adoc
> +If you want to load sample data and dashboards and explore its Superset's functionality, proceed to the next step.
```suggestion
If you want to load sample data and dashboards and explore Superset's functionality, proceed to the next step.
```

2024-09-19 14:48 UTC, adwk67 commented on docs/modules/superset/pages/getting_started/installation.adoc
> +On this page you will install the Stackable Superset Operator as well as the commons, secret and listener operator which are required by all Stackable Operators.
```suggestion
On this page you will install the Stackable Superset Operator as well as the commons, secret and listener operators which are required by all Stackable Operators.
```

2024-09-22 20:53 UTC, fhennig commented
Thanks! All good suggestions.

2024-09-23 06:19 UTC, adwk67 approved these changes
LGTM!

2024-09-23 06:21 UTC, merged