feat: Support OPA role mapping
stackabletech/superset-operator pull request #582
Opened 2024-12-23 12:37 UTC by Maleware

# Description

Contains:
 - https://github.com/stackabletech/marispace-x/issues/97
    Opa role mapping according to linked ticket.

relies on https://github.com/stackabletech/docker-images/tree/feature/superset-opa-integration
## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] CRD changes approved
- [x] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
- [x] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2025-01-23 09:35 UTC, sbernauer requested changes
Did not try it out, but I like the nice kuttl test!

2025-01-23 09:35 UTC, sbernauer commented on rust/operator-binary/src/superset_controller.rs
> +    #[snafu(display("invalid OpaConfig"))]
```suggestion

    #[snafu(display("invalid OpaConfig"))]
```

2025-01-23 09:35 UTC, sbernauer commented on rust/operator-binary/src/superset_controller.rs
> +    // Adding opa configuration properties to config_properties.
If we let `as_config` return BTreeMap<String, String> instead we can do this:

One change: This will only set STACKABLE_OPA_PACKAGE in case the package is set (previously it was an empty string). The Python part needs to be able to handle this.

```patch
diff --git a/rust/operator-binary/src/authorization/opa.rs b/rust/operator-binary/src/authorization/opa.rs
index 6b5babd..8243a13 100644
--- a/rust/operator-binary/src/authorization/opa.rs
+++ b/rust/operator-binary/src/authorization/opa.rs
@@ -40,33 +40,32 @@ impl SupersetOpaConfigResolved {
         })
     }
 
-    // Adding necessary configurations. Imports are solved in config.rs
-    pub fn as_config(&self) -> BTreeMap<String, Option<String>> {
-        BTreeMap::from([
+    // Adding necessary configurations. Imports are solved in config.rs.
+    pub fn as_config(&self) -> BTreeMap<String, String> {
+        let mut config = BTreeMap::from([
             (
                 "CUSTOM_SECURITY_MANAGER".to_string(),
-                Some("OpaSupersetSecurityManager".to_string()),
-            ),
-            (
-                "STACKABLE_OPA_RULE".to_string(),
-                Some("user_roles".to_string()),
+                "OpaSupersetSecurityManager".to_string(),
             ),
+            ("STACKABLE_OPA_RULE".to_string(), "user_roles".to_string()),
             (
                 "STACKABLE_OPA_BASE_URL".to_string(),
-                Some(self.opa_base_url.to_owned()),
-            ),
-            (
-                "STACKABLE_OPA_PACKAGE".to_string(),
-                self.opa_package.to_owned(),
+                self.opa_base_url.to_owned(),
             ),
             (
                 "STACKABLE_OPA_CACHE_MAX_ENTRIES".to_string(),
-                Some(self.cache_max_entries.to_string()),
+                self.cache_max_entries.to_string(),
             ),
             (
                 "STACKABLE_OPA_CACHE_ENTRY_TTL".to_string(),
-                Some(self.cache_ttl.as_secs().to_string()),
+                self.cache_ttl.as_secs().to_string(),
             ),
-        ])
+        ]);
+
+        if let Some(opa_package) = &self.opa_package {
+            config.insert("STACKABLE_OPA_PACKAGE".to_string(), opa_package.clone());
+        }
+
+        config
     }
 }
diff --git a/rust/operator-binary/src/superset_controller.rs b/rust/operator-binary/src/superset_controller.rs
index 223824b..ecad920 100644
--- a/rust/operator-binary/src/superset_controller.rs
+++ b/rust/operator-binary/src/superset_controller.rs
@@ -576,11 +576,10 @@ fn build_rolegroup_config_map(
     // Adding opa configuration properties to config_properties.
     // This will be injected as key/value pair in superset_config.py
     if let Some(opa_config) = superset_opa_config {
-        for (k, v) in opa_config.as_config() {
-            config_properties.insert(k, v.unwrap_or_default());
-        }
         // If opa role mapping is configured, insert CustomOpaSecurityManager import
-        imports.append(&mut (*OPA_IMPORTS).to_vec())
+        imports.extend(OPA_IMPORTS);
+
+        config_properties.extend(opa_config.as_config());
     }
 
     // The order here should be kept in order to preserve overrides.
```

2025-01-23 09:35 UTC, sbernauer commented on tests/templates/kuttl/opa/40_superset.yaml.j2
> +      opa:
Remember to update

2025-01-23 09:35 UTC, sbernauer commented on tests/templates/kuttl/opa/40_superset.yaml.j2
> +        cache: {}
I think most users will not tweak the cache, so it's good to test the happy path I guess
```suggestion
```

2025-01-23 09:35 UTC, sbernauer commented on tests/templates/kuttl/opa/50-get-user-roles-cm
We might want to have some sort of file extension

2025-01-23 09:35 UTC, sbernauer commented on tests/templates/kuttl/opa/get_user_roles.py
Thanks for correctly naming all files with a number before!
Can you please also put a 50_ before this file?

2025-01-31 17:43 UTC, labrenbe commented on Cargo.toml
> +stackable-operator = { git = "https://github.com/stackabletech//operator-rs.git", branch = "feat/cache" }
done

2025-01-31 17:44 UTC, labrenbe commented on rust/operator-binary/src/superset_controller.rs
> +    // Adding opa configuration properties to config_properties.
I've made the suggested changes and renamed some config entries to be more in line with our airflow-operator.

2025-02-17 10:59 UTC, razvan commented on tests/test-definition.yaml
> +      - 0.66.0
This is not a full review, just wanted to mention that the latest supported OPA version is now `1.0.1`

See https://github.com/stackabletech/docker-images/issues/998

2025-02-25 13:38 UTC, sbernauer reviewed
Thanks for addressing the review, I marked the corresponding discussions as resolved.
Only 3 old discussions remaining

2025-02-25 17:01 UTC, razvan commented
Tests with custom image are :green_circle: 

```
--- PASS: kuttl (1564.47s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/cluster-operation_superset-latest-4.0.2,oci.stackable.tech_razvan_superset_4.1.1-stackable0.0.0-dev_openshift-false (130.44s)
        --- PASS: kuttl/harness/ldap_superset-4.0.2,oci.stackable.tech_razvan_superset_4.0.2-stackable0.0.0-dev_ldap-authentication-no-tls_openshift-false (121.91s)
        --- PASS: kuttl/harness/logging_superset-4.0.2,oci.stackable.tech_razvan_superset_4.0.2-stackable0.0.0-dev_openshift-false (234.49s)
        --- PASS: kuttl/harness/smoke_superset-4.0.2,oci.stackable.tech_razvan_superset_4.0.2-stackable0.0.0-dev_openshift-false (126.07s)
        --- PASS: kuttl/harness/oidc_superset-4.0.2,oci.stackable.tech_razvan_superset_4.0.2-stackable0.0.0-dev_openshift-false (220.32s)
        --- PASS: kuttl/harness/ldap_superset-4.0.2,oci.stackable.tech_razvan_superset_4.0.2-stackable0.0.0-dev_ldap-authentication-server-verification-tls_openshift-false (125.52s)
        --- PASS: kuttl/harness/opa_superset-4.0.2,oci.stackable.tech_razvan_superset_4.0.2-stackable0.0.0-dev_opa-1.0.1_openshift-false (231.31s)
        --- PASS: kuttl/harness/ldap_superset-4.0.2,oci.stackable.tech_razvan_superset_4.0.2-stackable0.0.0-dev_ldap-authentication-insecure-tls_openshift-false (122.19s)
        --- PASS: kuttl/harness/druid-connection_superset-4.0.2,oci.stackable.tech_razvan_superset_4.0.2-stackable0.0.0-dev_openshift-false (107.36s)
        --- PASS: kuttl/harness/resources_superset-latest-4.0.2,oci.stackable.tech_razvan_superset_4.1.1-stackable0.0.0-dev_openshift-false (144.83s)
PASS
```

2025-02-26 07:57 UTC, sbernauer commented on rust/crd/src/lib.rs
> +    pub role_mapping_from_opa: Option<SupersetOpaRoleMappingConfig>,
Thanks!

2025-02-26 07:59 UTC, sbernauer commented on rust/operator-binary/src/authorization/opa.rs
> +        };
I was actually thinking the same, but haven't looked into the Python part at all - so I assumed it needs to be this way ^^
So +1 from me :+1:

2025-02-26 09:28 UTC, razvan commented on rust/operator-binary/src/authorization/opa.rs
> +        };
[done](https://github.com/stackabletech/superset-operator/pull/582/commits/95c22b1fd730989f150ca5b12fcc2cfca263663d)

```
--- PASS: kuttl (214.69s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/opa_superset-4.0.2,oci.stackable.tech_razvan_superset_4.0.2-stackable0.0.0-dev_opa-1.0.1_openshift-false (214.68s)
PASS
```

2025-02-26 10:02 UTC, sbernauer commented on rust/operator-binary/src/authorization/opa.rs
> +        };
Thanks!

2025-02-26 10:16 UTC, sbernauer requested changes
Did look into the docs and tests now

2025-02-26 10:16 UTC, sbernauer commented on docs/modules/superset/pages/usage-guide/security.adoc
> +=== [[OPA]] OPA role mapping
optional: I personally find that easier to read.
The suggestion also changes it to lower-case, *should* hopefully be fine
```suggestion
[opa]
=== OPA role mapping
```

2025-02-26 10:16 UTC, sbernauer commented on docs/modules/superset/pages/usage-guide/security.adoc
> +In order to map roles from OPA into Superset, we expect rego rules with a rule name `user_roles`.
```suggestion
In order to map roles from OPA into Superset, we expect rego rules with a rule named `user_roles`.
```

2025-02-26 10:16 UTC, sbernauer commented on docs/modules/superset/pages/usage-guide/security.adoc
> +In the below example two users `admin` and `testuser` have roles defined as rego rule in Rego v1 to be compliant with OPA v1.0.0 release.
```suggestion
In the below example two users `admin` and `testuser` have roles defined as rego rule.
```

2025-02-26 10:16 UTC, sbernauer commented on docs/modules/superset/pages/usage-guide/security.adoc
> +Mounting this `configMap` in superset as follows:
We are not mounting it...
```suggestion
You can instruct Superset to use the rego rule as follows:
```

2025-02-26 10:16 UTC, sbernauer commented on docs/modules/superset/pages/usage-guide/security.adoc
> +    import rego.v1
We are on OPA 1.0.0 already
```suggestion
```

2025-02-26 10:16 UTC, sbernauer commented on docs/modules/superset/pages/usage-guide/security.adoc
> +IMPORTANT: Only role mapping is enabled!
Can you please mention that the responsibility to create the roles is up to the Superset admin?
And that an error will be logged and the role is not added to the user in this case?

2025-02-26 10:16 UTC, sbernauer commented on rust/operator-binary/src/config.rs
> +    &["from opa_authorizer.opa_manager import OpaSupersetSecurityManager"];
Can you please move that constant into `rust/operator-binary/src/authorization/opa.rs`?

2025-02-26 10:16 UTC, sbernauer commented on tests/templates/kuttl/opa/40_superset.yaml.j2
> +        cache: {}
No idea why this was closed ^^

2025-02-26 10:16 UTC, sbernauer commented on tests/templates/kuttl/smoke/30-install-superset.yaml.j2
What's the reason we modify the smoke test here?
To me that looks like a leftover, the changes here are already in the `opa` test

2025-02-26 10:16 UTC, sbernauer commented on tests/test-definition.yaml
> +  - name: opa
I would prefer to rename it to `opa-latest`, as we are only testing against a single version for runtime reasons

2025-02-26 11:43 UTC, razvan commented on tests/test-definition.yaml
> +  - name: opa
Yeah, I [renamed](https://github.com/stackabletech/superset-operator/pull/582/commits/bcd774f60c865b535f7e8088169e16a585439bf5) the dimension and not the test. We may need to support multiple opa versions sometime.

2025-02-26 11:43 UTC, razvan commented on tests/templates/kuttl/smoke/30-install-superset.yaml.j2
Not sure what you mean here. Are these comments obsolete?

2025-02-26 11:44 UTC, razvan commented on rust/operator-binary/src/config.rs
> +    &["from opa_authorizer.opa_manager import OpaSupersetSecurityManager"];
[done](https://github.com/stackabletech/superset-operator/pull/582/commits/0d078b1f4c8932fee75ced030db6b50ed75c39a4)

2025-02-26 11:44 UTC, razvan commented on docs/modules/superset/pages/usage-guide/security.adoc
> +    import rego.v1
[done](https://github.com/stackabletech/superset-operator/pull/582/commits/d69ff8b2325a5b1984240bada64f89d006c18cf9)

2025-02-26 11:44 UTC, razvan commented on docs/modules/superset/pages/usage-guide/security.adoc
> +IMPORTANT: Only role mapping is enabled!
I [reworded](https://github.com/stackabletech/superset-operator/pull/582/commits/d69ff8b2325a5b1984240bada64f89d006c18cf9) the entire section.

2025-02-26 12:33 UTC, sbernauer commented on tests/templates/kuttl/smoke/30-install-superset.yaml.j2
It's still relevant. I was wondering why we touch the file `tests/templates/kuttl/smoke/30-install-superset.yaml.j2` at all. I would prefer to not modify it in this PR, the smoke test should be unchanged

2025-02-26 12:50 UTC, razvan commented on tests/templates/kuttl/smoke/30-install-superset.yaml.j2
[done](https://github.com/stackabletech/superset-operator/pull/582/commits/1051900991c80cd36d51dfcae65691482c7f0a1b)

2025-02-26 13:24 UTC, sbernauer commented on tests/templates/kuttl/smoke/30-install-superset.yaml.j2
Thanks!

2025-02-26 14:22 UTC, sbernauer approved these changes
Many thanks. LGTM when tests pass

2025-02-26 14:22 UTC, sbernauer commented on rust/operator-binary/src/authorization/opa.rs
> +        // Get opa_base_url for later use in CustomOpaSecurityManager
I think the comment is now outdated. Once could argue it's value is small ;)
```suggestion
```

2025-02-26 14:22 UTC, sbernauer commented on rust/operator-binary/src/superset_controller.rs
> +    #[snafu(display("invalid OpaConfig"))]
```suggestion
    #[snafu(display("invalid OPA config"))]
```

2025-02-26 14:57 UTC, sbernauer submitted a review, later dismissed
LGTM when tests pass

2025-02-26 17:29 UTC, sbernauer approved these changes

2025-02-26 18:19 UTC, razvan commented
OpenShift test :green_circle: 

```
--- PASS: kuttl (315.53s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/opa_superset-4.1.1_opa-latest-1.0.1_openshift-true (314.71s)
PASS
```

2025-02-26 18:20 UTC, razvan commented
:green_circle: Integration tests: https://testing.stackable.tech/job/superset-operator-it-custom/13/

2025-02-26 18:40 UTC, sbernauer approved these changes

2025-02-26 18:44 UTC, merged

2025-02-27 11:46 UTC, lfrancke commented
Can you please link docs if we have any (sounds like we should) and add a release note snippet?

2025-02-27 11:49 UTC, sbernauer commented
Nightly docs: https://docs.stackable.tech/home/nightly/superset/usage-guide/security/#_opa_role_mapping

2025-03-31 16:09 UTC, lfrancke commented
@Techassi @labrenbe ping re: release notes please (even if they are already in the final ones)

2025-03-31 18:36 UTC, Techassi commented
The final release notes @NickLarsenNZ and I came up with are:

```adoc
* Apache Superset: Support Open Policy Agent role mapping. See #582.
```